package model.enums;

public enum GameObjectType
{
    JAZZ_SEEDS("Jazz Seeds"),
    CARROT_SEEDS("Carrot Seeds"),
    CAULIFLOWER_SEEDS("Cauliflower Seeds"),
    COFFEE_BEAN("Coffee Bean"),
    GARLIC_SEEDS("Garlic Seeds"),
    BEAN_STARTER("Bean Starter"),
    KALE_SEEDS("Kale Seeds"),
    PARSNIP_SEEDS("Parsnip Seeds"),
    POTATO_SEEDS("Potato Seeds"),
    RHUBARB_SEEDS("Rhubarb Seeds"),
    STRAWBERRY_SEEDS("Strawberry Seeds"),
    TULIP_BULB("Tulip Bulb"),
    RICE_SHOOT("Rice Shoot"),
    BLUEBERRY_SEEDS("Blueberry Seeds"),
    CORN_SEEDS("Corn Seeds"),
    HOPS_STARTER("Hops Starter"),
    PEPPER_SEEDS("Pepper Seeds"),
    MELON_SEEDS("Melon Seeds"),
    POPPY_SEEDS("Poppy Seeds"),
    RADISH_SEEDS("Radish Seeds"),
    RED_CABBAGE_SEEDS("Red Cabbage Seeds"),
    STARFRUIT_SEEDS("Starfruit Seeds"),
    SPANGLE_SEEDS("Spangle Seeds"),
    SUMMER_SQUASH_SEEDS("Summer Squash Seeds"),
    SUNFLOWER_SEEDS("Sunflower Seeds"),
    TOMATO_SEEDS("Tomato Seeds"),
    WHEAT_SEEDS("Wheat Seeds"),
    AMARANTH_SEEDS("Amaranth Seeds"),
    ARTICHOKE_SEEDS("Artichoke Seeds"),
    BEET_SEEDS("Beet Seeds"),
    BOK_CHOY_SEEDS("Bok Choy Seeds"),
    BROCCOLI_SEEDS("Broccoli Seeds"),
    CRANBERRY_SEEDS("Cranberry Seeds"),
    EGGPLANT_SEEDS("Eggplant Seeds"),
    FAIRY_SEEDS("Fairy Seeds"),
    GRAPE_STARTER("Grape Starter"),
    PUMPKIN_SEEDS("Pumpkin Seeds"),
    YAM_SEEDS("Yam Seeds"),
    RARE_SEED("Rare Seed"),
    POWERDMELON_SEEDS("Powdermelon Seeds"),
    ANCIENT_SEEDS("Ancient Seeds"),
    MIXED_SEEDS("Mixed Seeds"),

    BLUE_JAZZ_CROP("Blue Jazz"),
    CARROT_CROP("Carrot"),
    CAULIFLOWER_CROP("Cauliflower"),
    COFFEE_BEAN_CROP("Coffee Bean"),
    GARLIC_CROP("Garlic"),
    GREEN_BEAN_CROP("Green Bean"),
    KALE_CROP("Kale"),
    PARSNIP_CROP("Parsnip"),
    POTATO_CROP("Potato"),
    RHUBARB_CROP("Rhubarb"),
    STRAWBERRY_CROP("Strawberry"),
    TULIP_CROP("Tulip"),
    UNMILLED_RICE_CROP("Unmilled Rice"),
    BLUEBERRY_CROP("Blueberry"),
    CORN_CROP("Corn"),
    HOPS_CROP("Hops"),
    HOT_PEPPER_CROP("Hot Pepper"),
    MELON_CROP("Melon"),
    POPPY_CROP("Poppy"),
    RADISH_CROP("Radish"),
    RED_CABBAGE_CROP("Red Cabbage"),
    STARFRUIT_CROP("Starfruit"),
    SUMMER_SPANGLE_CROP("Summer Spangle"),
    SUMMER_SQUASH_CROP("Summer Squash"),
    SUNFLOWER_CROP("Sunflower"),
    TOMATO_CROP("Tomato"),
    WHEAT_CROP("Wheat"),
    AMARANTH_CROP("Amaranth"),
    ARTICHOKE_CROP("Artichoke"),
    BEET_CROP("Beet"),
    BOK_CHOY_CROP("Bok Choy"),
    BROCCOLI_CROP("Broccoli"),
    CRANBERRIES_CROP("Cranberries"),
    EGGPLANT_CROP("Eggplant"),
    FAIRY_ROSE_CROP("Fairy Rose"),
    GRAPE_CROP("Grape"),
    PUMPKIN_CROP("Pumpkin"),
    YAM_CROP("Yam"),
    SWEET_GEM_BERRY_CROP("Sweet Gem Berry"),
    POWDERMELON_CROP("Powdermelon"),
    ANCIENT_FRUIT_CROP("Ancient Fruit"),

    QUARTZ("Quartz"),
    EARTH_CRYSTAL("Earth Crystal"),
    FROZEN_TEAR("Frozen Tear"),
    FIRE_QUARTZ("Fire Quartz"),
    EMERALD("Emerald"),
    AQUAMARINE("Aquamarine"),
    RUBY("Ruby"),
    AMETHYST("Amethyst"),
    TOPAZ("Topaz"),
    JADE("Jade"),
    DIAMOND("Diamond"),
    PRISMATIC_SHARD("Prismatic Shard"),
    COPPER("Copper"),
    IRON("Iron"),
    GOLD("Gold"),
    IRIDIUM("Iridium"),

    COMMON_MUSHROOM_FORAGING_CROP("Common Mushroom"),
    DAFFODIL_FORAGING_CROP("Daffodil"),
    DANDELION_FORAGING_CROP("Dandelion"),
    LEEK_FORAGING_CROP("Leek"),
    MOREL_FORAGING_CROP("Morel"),
    SALMONBERRY_FORAGING_CROP("Salmonberry"),
    SPRING_ONION_FORAGING_CROP("Spring Onion"),
    WILD_HORSERADISH_FORAGING_CROP("Wild Horseradish"),
    FIDDLEHEAD_FERN_FORAGING_CROP("Fiddlehead Fern"),
    GRAPE_FORAGING_CROP("Grape"),
    RED_MUSHROOM_FORAGING_CROP("Red Mushroom"),
    SPICE_BERRY_FORAGING_CROP("Spice Berry"),
    SWEET_PEA_FORAGING_CROP("Sweet Pea"),
    BLACKBERRY_FORAGING_CROP("Blackberry"),
    CHANTERELLE_FORAGING_CROP("Chanterelle"),
    HAZELNUT_FORAGING_CROP("Hazelnut"),
    PURPLE_MUSHROOM_FORAGING_CROP("Purple Mushroom"),
    WILD_PLUM_FORAGING_CROP("Wild Plum"),
    CROCUS_FORAGING_CROP("Crocus"),
    CRYSTAL_FRUIT_FORAGING_CROP("Crystal Fruit"),
    HOLLY_FORAGING_CROP("Holly"),
    SNOW_YAM_FORAGING_CROP("Snow Yam"),
    WINTER_ROOT_FORAGING_CROP("Winter Root"),

    APRICOT_TREE("Apricot Tree"),
    CHERRY_TREE("Cherry Tree"),
    BANANA_TREE("Banana Tree"),
    MANGO_TREE("Mango Tree"),
    ORANGE_TREE("Orange Tree"),
    PEACH_TREE("Peach Tree"),
    APPLE_TREE("Apple Tree"),
    POMEGRANATE_TREE("Pomegranate Tree"),
    OAK_TREE("Oak Tree"),
    MAPLE_TREE("Maple Tree"),
    PINE_TREE("Pine Tree"),
    MAHOGANY_TREE("Mahogany Tree"),
    MUSHROOM_TREE("Mushroom Tree"),
    MYSTIC_TREE("Mystic Tree"),
    ACORNS_TREE("Acorns"),

    Spring_MIXED_SEED("Spring Mixed Seed"),
    SUMMER_MIXED_SEED("Summer Mixed Seed"),
    FALL_MIXED_SEED("Fall Mixed Seed"),
    WINTER_MIXED_SEED("Winter Mixed Seed"),

    EGG("egg"),
    SARDINE("sardine"),
    SALMON("salmon"),
    WHEAT("wheat"),
    LEEK("leek"),
    DANDELION("dandelion"),
    MILK("milk"),
    PUMPKIN("pumpkin"),
    WHEAT_FLOWER("wheat flower"),
    TOMATO("tomato"),
    CHEESE("cheese"),
    CORN("corn"),
    RICE("rice"),
    FIBER("fiber"),
    COFFEE("coffee"),
    SUGAR("sugar"),
    POTATO("potato"),
    OIL("oil"),
    BLUEBERRY("blueberry"),
    MELON("melon"),
    APRICOT("apricot"),
    CHERRY("cherry"),
    BANANA("banana"),
    MANGO("mango"),
    ORANGE("orange"),
    PEACH("peach"),
    POMEGRANATE("pomegranate"),
    APPLE("apple"),
    OAK_RESIN("oak resin"),
    MAPLE_SYRUP("maple syrup"),
    PINE_TAR("pine tar"),
    SAP("sap"),
    COMMON_MUSHROOM("common mushroom"),
    MYSTIC_SYRUP("mystic syrup"),
    RED_CABBAGE("red cabbage"),
    RADISH("radish"),
    AMARANTH("amaranth"),
    KALE("kale"),
    BEET("beet"),
    OMELET("omelet"),
    PARSNIP("parsnip"),
    BREAD("bread"),
    CARROT("carrot"),
    EGGPLANT("eggplant"),
    HASH_BROWN("hash brown"),
    FLOUNDER("flounder"),
    MIDNIGHT_CARP("midnight carp"),

    FRIED_EGG("fried egg"),
    BAKED_FISH("baked fish"),
    SALAD("salad"),
    PUMPKIN_PIE("pumpkin pie"),
    SPAGHETTI("spaghetti"),
    PIZZA("pizza"),
    TORTILLA("tortilla"),
    MAKI_ROLL("maki roll"),
    TRIPLE_SHOT_ESPRESSO("triple shot espresso"),
    COOKIE("cookie"),
    PANCAKE("pancake"),
    FRUIT_SALAD("fruit salad"),
    RED_PLATE("red plate"),
    SALMON_DINNER("salmon dinner"),
    VEGETABLE_MEDLEY("vegetable medley"),
    FARMER_LUNCH("farmer's lunch"),
    SURVIVAL_BURGER("survival burger"),
    DISH_O_THE_SEA("dish O' the Sea"),
    SEAFORM_PUDDING("seaform pudding"),
    MINER_TREAT("miner's treat"),

    COPPER_ORE("copper ore"),
    COAL("coal"),
    IRON_ORE("iron ore"),
    GOLD_ORE("gold ore"),
    COPPER_BAR("copper bar"),
    IRON_BAR("iron bar"),
    GOLD_BAR("gold bar"),
    IRIDIUM_BAR("iridium bar"),
    WOOD("wood"),
    STONE("stone"),
    IRIDIUM_ORE("iridium ore"),
    ACORN("acorn"),
    MAPLE_SEED("maple seed"),
    PINE_CONE("pine cone"),
    MAHOGANY_SEED("mahogany seed"),

    CHERRY_BOMB("cherry bomb"),
    BOMB("bomb"),
    MEGA_BOMB("mega bomb"),
    SPRINKLER("sprinkler"),
    QUALITY_SPRINKLER("quality sprinkler"),
    IRIDIUM_SPRINKLER("iridium sprinkler"),
    CHARCOAL_KLIN("charcoal klin"),
    FURNACE("furnace"),
    SCARECROW("scarecrow"),
    DELUXE_SCARECROW("deluxe scarecrow"),
    BEE_HOUSE("bee house"),
    CHEESE_PRESS("cheese press"),
    KEG("keg"),
    LOOM("loom"),
    MAYONNAISE_MACHINE("mayonnaise machine"),
    OIL_MAKER("oil maker"),
    PRESERVES_JAR("preserves jar"),
    DEHYDRATOR("dehydrator"),
    FISH_SMOKER("fish smoker"),
    MYSTIC_TREE_SEED("mystic tree seed"),

    HONEY("honey"),
    GOAT_CHEESE("goat cheese"),
    BEER("beer"),
    VINEGAR("vinegar"),
    JUICE("juice"),
    MEAD("mead"),
    PALE_ALE("pale ale"),
    WINE("wine"),
    DRIED_MUSHROOM("dried mushroom"),
    DRIED_FRUIT("dried fruit"),
    CLOTH("cloth"),
    MAYONNAISE("mayonnaise"),
    DUCK_MAYONNAISE("duck mayonnaise"),
    DINOSAUR_MAYONNAISE("dinosaur mayonnaise"),
    TRUFFLE_OIL("truffle oil"),
    PICKLE("pickle"),
    JELLY("jelly"),
    SMOKED_FISH("smoothed fish"),
    GRAPE("grape"),
    LARGE_MILK("large milk"),
    LARGE_GOAT_MILK("large goat milk"),
    LARGE_EGG("large egg"),
    DUCK_EGG("duck egg"),
    DINOSAUR_EGG("dinosaur egg"),
    TRUFFLE("truffle"),
    SUNFLOWER("sunflower"),
    FISH("Fish"),
    FLOWER("Flower"),
    HEART("Heart"),

    Apricot_Sapling("apricot_sapling"),
    Cherry_Sapling("cherry sapling"),
    Banana_Sapling("banana sapling"),
    Mango_Sapling("mango sapling"),
    Orange_Sapling("orange sapling"),
    Peach_Sapling("peach sapling"),
    Apple_Sapling("apple sapling"),
    Pomegranate_Sapling("pomegranate sapling"),
    Acorns("acorns"),
    Maple_Seeds("maple seeds"),
    Pine_Cones("pine cones"),
    Mahogany_Seeds("mahogany seeds"),
    Mushroom_Tree_Seeds("mushroom tree seeds"),
    Mystic_Tree_Seed("mystic tree seed"),

    FERTILIZER("fertilizer"),

    CHERRY_BOMB_RECIPE("Cherry Bomb"),
    BOMB_RECIPE("Bomb"),
    MEGA_BOMB_RECIPE("Mega Bomb"),
    SPRINKLER_RECIPE("Sprinkler"),
    QUALITY_SPRINKLER_RECIPE("Quality Sprinkler"),
    IRIDIUM_SPRINKLER_RECIPE("Iridium Sprinkler"),
    CHARCOAL_KILN_RECIPE("Charcoal Klin"),
    FURNACE_RECIPE("Furnace"),
    SCARECROW_RECIPE("Scarecrow"),
    DELUXE_SCARECROW_RECIPE("Deluxe Scarecrow"),
    BEE_HOUSE_RECIPE("Bee House"),
    CHEESE_PRESS_RECIPE("Cheese Press"),
    KEG_RECIPE("Keg"),
    LOOM_RECIPE("Loom"),
    MAYONNAISE_MACHINE_RECIPE("Mayonnaise Machine"),
    OIL_MAKER_RECIPE("Oil Maker"),
    PRESERVES_JAR_RECIPE("Preserves Jar"),
    DEHYDRATOR_RECIPE("Dehydrator"),
    GRASS_STARTER_RECIPE("Grass Starter"),
    FISH_SMOKER_RECIPE("Fish Smoker"),
    MYSTIC_TREE_SEED_RECIPE("Mystic Tree Seed"),

    WOOL("wool"),
    GOLD_COIN("gold coin"),
    Automating_Iridium_WateringCan("automating iridium watering can"),
    HARD_WOOD("hard wood"),
    SALMON_DINNER_RECIPE("salmon dinner recipe"),

    ;

    private final String name;

    GameObjectType(String name)
    {
        this.name = name;
    }

    @Override
    public String toString()
    {
        return name;
    }

    public static GameObjectType getGameObjectType(String name)
    {
        for (GameObjectType gameObjectType : GameObjectType.values())
        {
            if (gameObjectType.name().equalsIgnoreCase(name))
            {
                return gameObjectType;
            }
        }
        return null;
    }
}
