package model.enums;

public enum GameObjectType {
    JAZZ_SEEDS("Jazz Seeds"),
    CARROT_SEEDS("Carrot Seeds"),
    CAULIFLOWER_SEEDS("Cauliflower Seeds"),
    COFFEE_BEAN("Coffee Bean"),
    GARLIC_SEEDS("Garlic Seeds"),
    BEAN_STARTER("Bean Starter"),
    KALE_SEEDS("Kale Seeds"),
    PARSNIP_SEEDS("Parsnip Seeds"),
    POTATO_SEEDS("Potato Seeds"),
    RHUBARB_SEEDS("Rhubarb Seeds"),
    STRAWBERRY_SEEDS("Strawberry Seeds"),
    TULIP_BULB("Tulip Bulb"),
    RICE_SHOOT("Rice Shoot"),
    BLUEBERRY_SEEDS("Blueberry Seeds"),
    CORN_SEEDS("Corn Seeds"),
    HOPS_STARTER("Hops Starter"),
    PEPPER_SEEDS("Pepper Seeds"),
    MELON_SEEDS("Melon Seeds"),
    POPPY_SEEDS("Poppy Seeds"),
    RADISH_SEEDS("Radish Seeds"),
    RED_CABBAGE_SEEDS("Red Cabbage Seeds"),
    STARFRUIT_SEEDS("Starfruit Seeds"),
    SPANGLE_SEEDS("Spangle Seeds"),
    SUMMER_SQUASH_SEEDS("Summer Squash Seeds"),
    SUNFLOWER_SEEDS("Sunflower Seeds"),
    TOMATO_SEEDS("Tomato Seeds"),
    WHEAT_SEEDS("Wheat Seeds"),
    AMARANTH_SEEDS("Amaranth Seeds"),
    ARTICHOKE_SEEDS("Artichoke Seeds"),
    BEET_SEEDS("Beet Seeds"),
    BOK_CHOY_SEEDS("Bok Choy Seeds"),
    BROCCOLI_SEEDS("Broccoli Seeds"),
    CRANBERRY_SEEDS("Cranberry Seeds"),
    EGGPLANT_SEEDS("Eggplant Seeds"),
    FAIRY_SEEDS("Fairy Seeds"),
    GRAPE_STARTER("Grape Starter"),
    PUMPKIN_SEEDS("Pumpkin Seeds"),
    YAM_SEEDS("Yam Seeds"),
    RARE_SEED("Rare Seed"),
    POWERDMELON_SEEDS("Powdermelon Seeds"),
    ANCIENT_SEEDS("Ancient Seeds"),
    MIXED_SEEDS("Mixed Seeds"),

    BLUE_JAZZ_CROP("Blue Jazz"),
    CARROT_CROP("Carrot"),
    CAULIFLOWER_CROP("Cauliflower"),
    COFFEE_BEAN_CROP("Coffee Bean"),
    GARLIC_CROP("Garlic"),
    GREEN_BEAN_CROP("Green Bean"),
    KALE_CROP("Kale"),
    PARSNIP_CROP("Parsnip"),
    POTATO_CROP("Potato"),
    RHUBARB_CROP("Rhubarb"),
    STRAWBERRY_CROP("Strawberry"),
    TULIP_CROP("Tulip"),
    UNMILLED_RICE_CROP("Unmilled Rice"),
    BLUEBERRY_CROP("Blueberry"),
    CORN_CROP("Corn"),
    HOPS_CROP("Hops"),
    HOT_PEPPER_CROP("Hot Pepper"),
    MELON_CROP("Melon"),
    POPPY_CROP("Poppy"),
    RADISH_CROP("Radish"),
    RED_CABBAGE_CROP("Red Cabbage"),
    STARFRUIT_CROP("Starfruit"),
    SUMMER_SPANGLE_CROP("Summer Spangle"),
    SUMMER_SQUASH_CROP("Summer Squash"),
    SUNFLOWER_CROP("Sunflower"),
    TOMATO_CROP("Tomato"),
    WHEAT_CROP("Wheat"),
    AMARANTH_CROP("Amaranth"),
    ARTICHOKE_CROP("Artichoke"),
    BEET_CROP("Beet"),
    BOK_CHOY_CROP("Bok Choy"),
    BROCCOLI_CROP("Broccoli"),
    CRANBERRIES_CROP("Cranberries"),
    EGGPLANT_CROP("Eggplant"),
    FAIRY_ROSE_CROP("Fairy Rose"),
    GRAPE_CROP("Grape"),
    PUMPKIN_CROP("Pumpkin"),
    YAM_CROP("Yam"),
    SWEET_GEM_BERRY_CROP("Sweet Gem Berry"),
    POWDERMELON_CROP("Powdermelon"),
    ANCIENT_FRUIT_CROP("Ancient Fruit"),

    QUARTZ_MINERAL("Quartz"),
    EARTH_CRYSTAL_MINERAL("Earth Crystal"),
    FROZEN_TEAR_MINERAL("Frozen Tear"),
    FIRE_QUARTZ_MINERAL("Fire Quartz"),
    EMERALD_MINERAL("Emerald"),
    AQUAMARINE_MINERAL("Aquamarine"),
    RUBY_MINERAL("Ruby"),
    AMETHYST_MINERAL("Amethyst"),
    TOPAZ_MINERAL("Topaz"),
    JADE_MINERAL("Jade"),
    DIAMOND_MINERAL("Diamond"),
    PRISMATIC_SHARD_MINERAL("Prismatic Shard"),
    COPPER_MINERAL("Copper"),
    IRON_MINERAL("Iron"),
    GOLD_MINERAL("Gold"),
    IRIDIUM_MINERAL("Iridium"),
    COAL_MINERAL("Coal"),

    COMMON_MUSHROOM_FORAGING_CROP("Common Mushroom"),
    DAFFODIL_FORAGING_CROP("Daffodil"),
    DANDELION_FORAGING_CROP("Dandelion"),
    LEEK_FORAGING_CROP("Leek"),
    MOREL_FORAGING_CROP("Morel"),
    SALMONBERRY_FORAGING_CROP("Salmonberry"),
    SPRING_ONION_FORAGING_CROP("Spring Onion"),
    WILD_HORSERADISH_FORAGING_CROP("Wild Horseradish"),
    FIDDLEHEAD_FERN_FORAGING_CROP("Fiddlehead Fern"),
    GRAPE_FORAGING_CROP("Grape"),
    RED_MUSHROOM_FORAGING_CROP("Red Mushroom"),
    SPICE_BERRY_FORAGING_CROP("Spice Berry"),
    SWEET_PEA_FORAGING_CROP("Sweet Pea"),
    BLACKBERRY_FORAGING_CROP("Blackberry"),
    CHANTERELLE_FORAGING_CROP("Chanterelle"),
    HAZELNUT_FORAGING_CROP("Hazelnut"),
    PURPLE_MUSHROOM_FORAGING_CROP("Purple Mushroom"),
    WILD_PLUM_FORAGING_CROP("Wild Plum"),
    CROCUS_FORAGING_CROP("Crocus"),
    CRYSTAL_FRUIT_FORAGING_CROP("Crystal Fruit"),
    HOLLY_FORAGING_CROP("Holly"),
    SNOW_YAM_FORAGING_CROP("Snow Yam"),
    WINTER_ROOT_FORAGING_CROP("Winter Root"),

    ;

    private final String name;

    GameObjectType(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}
